#version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-data:/tmp/kraft-combined-logs
      - ./kafka.properties:/tmp/kafka.properties  # â† Mount custom config
    environment:
      CLUSTER_ID: 4c355403-4234-4197-95cd-43f080484bfe
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command: >
      bash -c "
        if [ ! -f /tmp/kraft-combined-logs/meta.properties ]; then
          echo Formatting new Kafka cluster with ID 4c355403-4234-4197-95cd-43f080484bfe &&
          kafka-storage format --ignore-formatted --cluster-id=4c355403-4234-4197-95cd-43f080484bfe --config /tmp/kafka.properties;
        fi &&
        /etc/confluent/docker/run
      "

